apiVersion: v1  
kind: Service  
metadata:  
  name: hello-service
  labels:  
    app: hello-service
spec:  
  type: NodePort
  ports:  
    - name: http  
      port: 8080
      targetPort : 3000
      nodePort: 30000
  selector:  
    app: hello-service